/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rent;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.event.KeyEvent;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author kaniya
 */
public class Admin_EntendRent extends javax.swing.JFrame {

    /**
     * Creates new form CarReg
     */
    public Admin_EntendRent() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH); 
        CalDate.setDateFormatString("yyyy/MM/dd");
        autoId();
        get_table();
        get_extend_table();



        txtCarFee.setEnabled(false);
        txtDueDate.setEnabled(false);
        txtTotal.setEnabled(false);
        txtPaid.setEnabled(false);
        
        txtExtendID.setEnabled(false);
        CalDate.setEnabled(false);
        txtAditional.setEnabled(false);
        btnAdd2.setEnabled(false);
        txtLast.setEnabled(false);
        
        txtBalance.setEnabled(false);
        txtdays.setEnabled(false);
        btnAdd3.setEnabled(false);
        
    }
    
    Connection con;
    PreparedStatement pst;
    PreparedStatement ps;
    PreparedStatement ps1;
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtRentID = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        CalDate = new com.toedter.calendar.JDateChooser();
        txtCaeNumber = new javax.swing.JTextField();
        btnAdd2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtCarFee = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtDueDate = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtAditional = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtLast = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtExtendID = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtPaid = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtdays = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtBalance = new javax.swing.JTextField();
        btnAdd3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Rent ID");

        txtRentID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRentIDKeyPressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 0, 0));
        jLabel10.setText("Car Number");

        btnCancel.setBackground(new java.awt.Color(0, 0, 0));
        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Extend Date");

        btnAdd2.setBackground(new java.awt.Color(0, 0, 0));
        btnAdd2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAdd2.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd2.setText("Extend Rent");
        btnAdd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd2ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 0, 0));
        jLabel12.setText("Car Fee");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 0, 0));
        jLabel13.setText("Due Date");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Aditional Amount");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 0, 0));
        jLabel15.setText("Exist Totle");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("New Total Amount");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Extend ID");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 0, 0));
        jLabel17.setText("Last Paid");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Number of Day");

        txtdays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdaysActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("New Balance");

        btnAdd3.setBackground(new java.awt.Color(0, 0, 0));
        btnAdd3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAdd3.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd3.setText("Find");
        btnAdd3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CalDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtExtendID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtdays, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtBalance, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(txtLast, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAditional)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAdd3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAdd2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(226, 226, 226))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel17))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtTotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(txtDueDate, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCarFee, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCaeNumber, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRentID, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPaid))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRentID, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCaeNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCarFee, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDueDate, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPaid, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtExtendID, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CalDate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdays, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAditional, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLast, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addComponent(btnAdd3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 51));
        jLabel1.setText("Extend Rented Car - Admin");

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rent ID", "Car ID", "Customer ID", "Customer Name", "Car Fee", "Due Date", "Date", "Totlr Fee", "Paid Amount", "Balance", "Car Number", "Extend"
            }
        ));
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table1);

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Extend ID", "Rent ID", "Car Number", "Due Date", "Extend Date", "Aditional Amount", "New Last Total Balance"
            }
        ));
        table2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked
//         TODO add your handling code here:
//        int selectIndex;
//        TableModel d1 = (DefaultTableModel)table1.getModel();
//        selectIndex = table1.getSelectedRow();
//        
//        txtRentID.setText(d1.getValueAt(selectIndex, 0).toString());
//        comboCar.setSelectedItem(d1.getValueAt(selectIndex, 1).toString());
//        comboCustomer.setSelectedItem(d1.getValueAt(selectIndex, 2).toString());
//        txtCusName.setText(d1.getValueAt(selectIndex, 3).toString());
//        txtCarFee.setText(d1.getValueAt(selectIndex, 4).toString());
//        txtTotle.setText(d1.getValueAt(selectIndex, 6).toString());
//        txtPaid.setText(d1.getValueAt(selectIndex, 7).toString());
//        txtBalance.setText(d1.getValueAt(selectIndex, 7).toString());
        
        
    }//GEN-LAST:event_table1MouseClicked

    private void btnAdd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd2ActionPerformed

        PreparedStatement ps;
        PreparedStatement pb;

        String Extend_ID = txtExtendID.getText();
        String Rent_ID = txtRentID.getText();
        String CarNumber = txtCaeNumber.getText();
        String Duedate = txtDueDate.getText(); 
        String Aditional = txtAditional.getText();
        String Last = txtLast.getText();
        String paid = txtPaid.getText();
        String bLast_bal = txtBalance.getText();
        
        

        SimpleDateFormat date_format = new SimpleDateFormat("yyyy-MM-dd");
        String extend_date = date_format.format(CalDate.getDate());


        if (extend_date.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Customer");
        }else{
            try {

                Class.forName("com.mysql.jdbc.Driver");
                con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/carrent","root","");

                pst = (PreparedStatement) con.prepareStatement("insert into extend_rent(extend_id,rent_id,car_number,due_date,extend_date,aditional_amount,last_amount) values(?,?,?,?,?,?,?)");
                pst.setString(1, Extend_ID);
                pst.setString(2, Rent_ID);
                pst.setString(3, CarNumber);
                pst.setString(4, Duedate);
                pst.setString(5, extend_date);
                pst.setString(6, Aditional);
                pst.setString(7, Last);

                ps = (PreparedStatement) con.prepareStatement("update rent set  due_date=?, totle_fee=?, balance=?, extend=? where rent_id=?");
                ps.setString(1, extend_date);
                ps.setString(2, Last);
                ps.setString(3, bLast_bal);
                ps.setString(4, "Yes");
                ps.setString(5, Rent_ID);
                
                pb = (PreparedStatement) con.prepareStatement("update rent_backup set  due_date=?,totle_fee=?,balance=?,extend=? where rent_id=?");
                pb.setString(1, extend_date);
                pb.setString(2, Last);
                pb.setString(3, bLast_bal);
                pb.setString(4, "Yes");
                pb.setString(5, Rent_ID);

                pst.executeUpdate();
                ps.executeUpdate();
                pb.executeUpdate();

                JOptionPane.showMessageDialog(this, "Car Rent Extended Success");
                get_table();
                get_extend_table();
                autoId();
                

                txtRentID.setText("");
                txtCaeNumber.setText("");
                txtDueDate.setText("");
                txtAditional.setText("");
                txtLast.setText("");
                txtPaid.setText("");
                txtBalance.setText("");
                

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(CarReg.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(CarReg.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnAdd2ActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed

        
        adminPannel m = new adminPannel();
        this.hide();
        m.setVisible(true);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtRentIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRentIDKeyPressed

         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
            String Rent_id = txtRentID.getText();
            
            try {
                Class.forName("com.mysql.jdbc.Driver");
                con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/carrent","root","");
                ps = (PreparedStatement) con.prepareStatement("select * from rent where rent_id = ?");
                ps.setString(1, Rent_id);
                
                ResultSet r = ps.executeQuery();
                
                if (r.next() == false) {
                    JOptionPane.showMessageDialog(this, "Your Rent is Not Available");
                    
                    txtCarFee.setText("");
                    txtCaeNumber.setText("");
                    txtDueDate.setText("");
                    txtTotal.setText("");
                    txtPaid.setText("");
                    txtAditional.setText("");
                    txtLast.setText("");

                    
                    txtCarFee.setEnabled(false);
                    txtDueDate.setEnabled(false);
                    txtTotal.setEnabled(false);
                    txtPaid.setEnabled(false);
                    
                    txtBalance.setEnabled(false);
                    txtdays.setEnabled(false);
                    btnAdd3.setEnabled(false);
                    
                    txtExtendID.setEnabled(false);
                    CalDate.setEnabled(false);
                    txtAditional.setEnabled(false);
                    btnAdd2.setEnabled(false);
                    txtLast.setEnabled(false);
                    
                    
                    
                    
                }else{
                    
                    txtCarFee.setEnabled(true);
                    txtDueDate.setEnabled(true);
                    txtTotal.setEnabled(true);
                    txtPaid.setEnabled(true);

                    txtExtendID.setEnabled(true);
                    CalDate.setEnabled(true);
                    txtAditional.setEnabled(true);
                    btnAdd2.setEnabled(true);
                    txtLast.setEnabled(true);
                    
                    txtBalance.setEnabled(true);
                    txtdays.setEnabled(true);
                    btnAdd3.setEnabled(true);
                    
                    
                    String CarNumber = r.getString("car_number");
                    txtCaeNumber.setText(CarNumber.trim());
                    
                    String CarFee = r.getString("car_fee");
                    txtCarFee.setText(CarFee.trim());
                    
                    String DueDate = r.getString("due_date");
                    txtDueDate.setText(DueDate.trim());
                    
                    
                    String Totle = r.getString("totle_fee");
                    txtTotal.setText(Totle.trim());
                    
                    String Paid = r.getString("paid_amount");
                    txtPaid.setText(Paid.trim());
                    
                }
                
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(RentCar.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(RentCar.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        }
        
        
        
    }//GEN-LAST:event_txtRentIDKeyPressed

    private void txtdaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdaysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdaysActionPerformed

    private void btnAdd3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd3ActionPerformed
        
         SimpleDateFormat myFormat = new SimpleDateFormat("yyyy-MM-dd");
        
                    SimpleDateFormat date_format = new SimpleDateFormat("yyyy-MM-dd");;
                    String extend_date = date_format.format(CalDate.getDate());
                    
                    
                    String DueDate = txtDueDate.getText();
                    String CarFee = txtCarFee.getText();
                    String Totle = txtTotal.getText();
                    String paid = txtPaid.getText();

                    try {
                    Date ext_ddate = myFormat.parse(extend_date);
                    Date Due_date = myFormat.parse(DueDate);
                    long diff = ext_ddate.getTime() - Due_date.getTime();

                    int a = (int) TimeUnit.DAYS.convert(diff, TimeUnit.MILLISECONDS);
                    
                    txtdays.setText(String.valueOf(a));

                    int aditional = countTotle(a, Integer.parseInt(CarFee));
                    txtAditional.setText(String.valueOf(aditional));


                    int LastTotle =  countLastTotle(Integer.parseInt(Totle),aditional);
                    txtLast.setText(String.valueOf(LastTotle));
                    
                    int Last_bal = countBalance(LastTotle,Integer.parseInt(paid));
                    txtBalance.setText(String.valueOf(Last_bal));

                } catch (ParseException e) {
                    e.printStackTrace();
                }
        
        
        
    }//GEN-LAST:event_btnAdd3ActionPerformed

    private void table2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_table2MouseClicked

    
    public int countTotle(int days, int amount){
        int fee = 0;
        fee = days * amount;   
        return fee;
    }
    
    public int countBalance(int totle, int paid){
        int fee = 0;
        fee = totle - paid;   
        return fee;
    }
    public int countLastTotle(int totle, int aditional){
        int fee = 0;
        fee = totle + aditional;   
        return fee;
    }
    
    /**
     * @param args the command line arguments
     */
    public void get_table(){
        
        int c;
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/carrent","root","");
            pst = (PreparedStatement) con.prepareStatement("select * from rent");
            ResultSet rs = pst.executeQuery();
            
            ResultSetMetaData rm = rs.getMetaData();
            c = rm.getColumnCount();
            DefaultTableModel df = (DefaultTableModel)table1.getModel();
            df.setRowCount(0);
            
            while (rs.next()){
                Vector vector = new Vector();
                
                for (int i = 0; i <= c; i++) {
                    vector.add(rs.getString("rent_id"));
                    vector.add(rs.getString("car_id"));
                    vector.add(rs.getString("customer_id"));
                    vector.add(rs.getString("customer_name"));
                    vector.add(rs.getString("car_fee"));
                    vector.add(rs.getString("due_date"));
                    vector.add(rs.getString("trn_date"));
                    vector.add(rs.getString("totle_fee"));
                    vector.add(rs.getString("paid_amount"));
                    vector.add(rs.getString("balance"));
                    vector.add(rs.getString("car_number"));
                    vector.add(rs.getString("extend"));
                }
                df.addRow(vector);
            }
            
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Admin_EntendRent.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Admin_EntendRent.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }
    
    
    public void get_extend_table(){
        
        int c;
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/carrent","root","");
            pst = (PreparedStatement) con.prepareStatement("select * from extend_rent");
            ResultSet rs = pst.executeQuery();
            
            ResultSetMetaData rm = rs.getMetaData();
            c = rm.getColumnCount();
            DefaultTableModel df = (DefaultTableModel)table2.getModel();
            df.setRowCount(0);
            
            while (rs.next()){
                Vector vector = new Vector();
                
                for (int i = 0; i <= c; i++) {
                    vector.add(rs.getString("extend_id"));
                    vector.add(rs.getString("rent_id"));
                    vector.add(rs.getString("car_number"));
                    vector.add(rs.getString("due_date"));
                    vector.add(rs.getString("extend_date"));
                    vector.add(rs.getString("aditional_amount"));
                    vector.add(rs.getString("last_amount"));
                }
                df.addRow(vector);
            }
            
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Admin_EntendRent.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Admin_EntendRent.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }
    
    
    
    
   
    
    
    
    public void autoId(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/carrent","root","");
            Statement s = con.createStatement(); 
            
            ResultSet rs = s.executeQuery("select Max(extend_id) from extend_rent");
            rs.next();
            rs.getString("Max(extend_id)");
            
            if (rs.getString("Max(extend_id)")==null) {
                txtExtendID.setText("E0001");
            }
            else
            {
                long id = Long.parseLong(rs.getString("Max(extend_id)").substring(2,rs.getString("Max(extend_id)").length()));
                id++;
                txtExtendID.setText("E0" + String.format("%03d", id));
            }
            
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Admin_EntendRent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_EntendRent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_EntendRent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_EntendRent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_EntendRent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_EntendRent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser CalDate;
    private javax.swing.JButton btnAdd2;
    private javax.swing.JButton btnAdd3;
    private javax.swing.JButton btnCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable table1;
    private javax.swing.JTable table2;
    private javax.swing.JTextField txtAditional;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtCaeNumber;
    private javax.swing.JTextField txtCarFee;
    private javax.swing.JTextField txtDueDate;
    private javax.swing.JTextField txtExtendID;
    private javax.swing.JTextField txtLast;
    private javax.swing.JTextField txtPaid;
    private javax.swing.JTextField txtRentID;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtdays;
    // End of variables declaration//GEN-END:variables
}
