/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rent;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.event.KeyEvent;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author kaniya
 */
public class RentCar extends javax.swing.JFrame {

    /**
     * Creates new form CarReg
     */
    public RentCar() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH); 
        txtDueDate.setDateFormatString("yyyy/MM/dd");
        txtDate.setDateFormatString("yyyy/MM/dd");
        autoId();
        getCar();
        get_table();



        txtCusID.setEnabled(false);
        txtCusName.setEnabled(false);
        txtDueDate.setEnabled(false);
        txtTotle.setEnabled(false);
        txtPaid.setEnabled(false);
        txtBalance.setEnabled(false);
        txtDate.setEnabled(false);
        txtCarFee.setEnabled(false);
        btnCancel1.setEnabled(false);
        btnAdd2.setEnabled(false);
        txtCarNumber.setEnabled(false);
    }
    
    Connection con;
    PreparedStatement pst;
    PreparedStatement ps;
    PreparedStatement ps1;
   
    
    public void getCar(){
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/carrent","root","");
            pst = (PreparedStatement) con.prepareStatement("select * from carreg");
            ResultSet rs = pst.executeQuery();
            comboCar.removeAllItems();
            
            
            while(rs.next()){
                comboCar.addItem(rs.getString(2));
            }
            
            
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RentCar.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(RentCar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtRentID = new javax.swing.JTextField();
        txtCusName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtCarFee = new javax.swing.JTextField();
        txtTotle = new javax.swing.JTextField();
        txtPaid = new javax.swing.JTextField();
        comboCar = new javax.swing.JComboBox<>();
        txtBalance = new javax.swing.JTextField();
        txtDueDate = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        txtDate = new com.toedter.calendar.JDateChooser();
        txtAvailable = new javax.swing.JTextField();
        txtCusID = new javax.swing.JTextField();
        btnCancel1 = new javax.swing.JButton();
        btnAdd2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtCarNumber = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 204));
        jLabel2.setText("Rent ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 204));
        jLabel3.setText("Customer ID");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 204));
        jLabel4.setText("Customer Name");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 204));
        jLabel5.setText("Balance");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 204));
        jLabel6.setText("Car Fee Per(hr)");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 204));
        jLabel7.setText("Due Date");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 204));
        jLabel8.setText("Totle Fee");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 204));
        jLabel9.setText("Paid Amount");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 204));
        jLabel10.setText("Car ID");

        txtCarFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarFeeActionPerformed(evt);
            }
        });

        txtPaid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPaidKeyPressed(evt);
            }
        });

        comboCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCarActionPerformed(evt);
            }
        });

        txtDueDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDueDateFocusGained(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 204));
        jLabel11.setText("Date");

        txtCusID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCusIDKeyPressed(evt);
            }
        });

        btnCancel1.setBackground(new java.awt.Color(0, 0, 0));
        btnCancel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCancel1.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel1.setText("Get Fee");
        btnCancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancel1ActionPerformed(evt);
            }
        });

        btnAdd2.setBackground(new java.awt.Color(0, 0, 0));
        btnAdd2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAdd2.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd2.setText("Add Rent");
        btnAdd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd2ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 204));
        jLabel12.setText("Car Number");

        txtCarNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarNumberActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(0, 0, 0));
        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPaid, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                                    .addComponent(txtTotle)
                                    .addComponent(txtBalance)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDueDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCarNumber)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(comboCar, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtAvailable, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                                    .addComponent(btnCancel1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRentID)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtCusID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                                        .addComponent(txtCusName, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(txtDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCarFee, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(jLabel2)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAdd2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRentID, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboCar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCusID, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCusName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtCarNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCarFee, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDueDate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addComponent(btnCancel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtTotle, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txtPaid, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdd2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 51));
        jLabel1.setText("Rent Car -Admin");

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rent ID", "Car ID", "Customer ID", "Customer Name", "Car Fee", "Due Date", "Date", "Totlr Fee", "Paid Amount", "Balance", "Car Number"
            }
        ));
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 977, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        Main m = new Main();
        this.hide();
        m.setVisible(true);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked
//         TODO add your handling code here:
//        int selectIndex;
//        TableModel d1 = (DefaultTableModel)table1.getModel();
//        selectIndex = table1.getSelectedRow();
//        
//        txtRentID.setText(d1.getValueAt(selectIndex, 0).toString());
//        comboCar.setSelectedItem(d1.getValueAt(selectIndex, 1).toString());
//        comboCustomer.setSelectedItem(d1.getValueAt(selectIndex, 2).toString());
//        txtCusName.setText(d1.getValueAt(selectIndex, 3).toString());
//        txtCarFee.setText(d1.getValueAt(selectIndex, 4).toString());
//        txtTotle.setText(d1.getValueAt(selectIndex, 6).toString());
//        txtPaid.setText(d1.getValueAt(selectIndex, 7).toString());
//        txtBalance.setText(d1.getValueAt(selectIndex, 7).toString());
        
        
    }//GEN-LAST:event_table1MouseClicked

    private void comboCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCarActionPerformed

//       String id = "U0001";
        String id = comboCar.getSelectedItem().toString();
//            
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/carrent","root","");
            
            ps1 = (PreparedStatement) con.prepareStatement("select * from carreg where car_reg = ?");
            ps1.setString(1, id);
            
            ResultSet ra = ps1.executeQuery();
            

                
            if (ra.next() == false) {
                JOptionPane.showMessageDialog(this, "Car is Not Available");
            }else{
                String avl = ra.getString("available");
                txtAvailable.setText(avl.trim());
                
                String avlb = ra.getString("rent_fee");
                txtCarFee.setText(avlb.trim());
                
                String avlb1 = ra.getString("car_number");
                txtCarNumber.setText(avlb1.trim());
                
                if (avl.equals("Yes")) {
//                    txtCusID.setEnabled(false);
                    txtCusName.setEnabled(true);
                    txtCusID.setEnabled(true);
                    txtDueDate.setEnabled(true);
                    txtTotle.setEnabled(true);
                    txtPaid.setEnabled(true);
                    txtBalance.setEnabled(true);
                    txtDate.setEnabled(true);
                    txtCarFee.setEnabled(true);
                    txtCarNumber.setEnabled(true);
                    btnCancel1.setEnabled(true);
                    
                    
                    txtTotle.setText("");
                    txtPaid.setText("");
                    txtBalance.setText("");
                    
                    btnAdd2.setEnabled(false);
                    
                }else{
                    txtCarNumber.setEnabled(false);
                    txtCusID.setEnabled(false);
                    txtCusName.setEnabled(false);
                    txtDueDate.setEnabled(false);
                    txtTotle.setEnabled(false);
                    txtPaid.setEnabled(false);
                    txtBalance.setEnabled(false);
                    txtDate.setEnabled(false);
                    txtCarFee.setEnabled(false);
                    btnCancel1.setEnabled(false);
                    btnAdd2.setEnabled(false);
                }
            }
                   
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RentCar.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(RentCar.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }//GEN-LAST:event_comboCarActionPerformed

    private void txtCarFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarFeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarFeeActionPerformed

    private void txtCusIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCusIDKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
            String Cust_ID = txtCusID.getText();
            
            try {
                Class.forName("com.mysql.jdbc.Driver");
                con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/carrent","root","");
                ps = (PreparedStatement) con.prepareStatement("select * from customer where customer_id = ?");
                ps.setString(1, Cust_ID);
                
                ResultSet r = ps.executeQuery();
                
                if (r.next() == false) {
                    JOptionPane.showMessageDialog(this, "Customer is Not Available");
                    txtCusName.setText("");
                }else{
                    String avl = r.getString("name");
                    txtCusName.setText(avl.trim());

                }
                
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(RentCar.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(RentCar.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        }
    }//GEN-LAST:event_txtCusIDKeyPressed

    private void txtDueDateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDueDateFocusGained
 
    }//GEN-LAST:event_txtDueDateFocusGained

    private void btnCancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancel1ActionPerformed

        SimpleDateFormat myFormat = new SimpleDateFormat("yyyy-MM-dd");
        
        SimpleDateFormat date_format = new SimpleDateFormat("yyyy-MM-dd");
        String due_date = date_format.format(txtDueDate.getDate());
        
        SimpleDateFormat date_format2 = new SimpleDateFormat("yyyy-MM-dd");
        String trn_date = date_format.format(txtDate.getDate());

                try {
                Date date1 = myFormat.parse(trn_date);
                Date date2 = myFormat.parse(due_date);
                long diff = date2.getTime() - date1.getTime();

                int a = (int) TimeUnit.DAYS.convert(diff, TimeUnit.MILLISECONDS);

                int fee = Integer.parseInt(txtCarFee.getText()); 
                int totle = countTotle(a,fee);

                String cus_id = txtCusID.getText();
                String cus_name = txtCusName.getText();

                if (cus_name.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Please Add Customer");
                }else{
                    txtTotle.setText(String.valueOf(totle));
                    ;
                }    

            } catch (ParseException e) {
                e.printStackTrace();
            }
        
 
    }//GEN-LAST:event_btnCancel1ActionPerformed

    private void btnAdd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd2ActionPerformed
        
        
        PreparedStatement ps;
        PreparedStatement pb;
            
            String RentID = txtRentID.getText();
            String Car = comboCar.getSelectedItem().toString();
            String CusID = txtCusID.getText();
            String CusName = txtCusName.getText();
            String CarFee = txtCarFee.getText();
            String car_number = txtCarNumber.getText();
            
            SimpleDateFormat date_format = new SimpleDateFormat("yyyy-MM-dd");
            String due_date = date_format.format(txtDueDate.getDate());
        
            SimpleDateFormat date_format2 = new SimpleDateFormat("yyyy-MM-dd");
            String trn_date = date_format.format(txtDate.getDate());
            
            String Totle = txtTotle.getText();
            String Paid = txtPaid.getText();
            String balance = txtBalance.getText();       
              
            if (CusName.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please Enter Customer");
            }else if (Totle.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please Find Totle");
            }else if (Paid.isEmpty()) {
                JOptionPane.showMessageDialog(this, "if you need to rent Car, You need to Pay");
            }else{
                 try {

                        Class.forName("com.mysql.jdbc.Driver");
                        con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/carrent","root","");

                        pst = (PreparedStatement) con.prepareStatement("insert into rent(rent_id,car_id,customer_id,customer_name,car_fee,due_date,totle_fee,paid_amount,balance,trn_date,car_number,extend) values(?,?,?,?,?,?,?,?,?,?,?,?)");
                        pst.setString(1, RentID);
                        pst.setString(2, Car);
                        pst.setString(3, CusID);
                        pst.setString(4, CusName);
                        pst.setString(5, CarFee);
                        pst.setString(6, due_date);
                        pst.setString(7, Totle);
                        pst.setString(8, Paid);
                        pst.setString(9, balance);
                        pst.setString(10, trn_date);
                        pst.setString(11, car_number);
                        pst.setString(12, "No");
                        
                        pb = (PreparedStatement) con.prepareStatement("insert into rent_backup(rent_id,car_id,customer_id,customer_name,car_fee,due_date,totle_fee,paid_amount,balance,trn_date,car_number,extend) values(?,?,?,?,?,?,?,?,?,?,?,?)");
                        pb.setString(1, RentID);
                        pb.setString(2, Car);
                        pb.setString(3, CusID);
                        pb.setString(4, CusName);
                        pb.setString(5, CarFee);
                        pb.setString(6, due_date);
                        pb.setString(7, Totle);
                        pb.setString(8, Paid);
                        pb.setString(9, balance);
                        pb.setString(10, trn_date);
                        pb.setString(11, car_number);
                        pb.setString(12, "No");
                        
                        
                        
                        
                        ps = (PreparedStatement) con.prepareStatement("update carreg set  available=? where car_reg=?");
                        ps.setString(1, "No");
                        ps.setString(2, Car);

                        pst.executeUpdate();
                        ps.executeUpdate();
                        pb.executeUpdate();
                        
                        JOptionPane.showMessageDialog(this, "Car Rent Success");
                        get_table();
                        autoId();
                        
                        txtCusName.setText("");
                        txtCusID.setText("");
                        txtTotle.setText("");
                        txtPaid.setText("");
                        txtBalance.setText("");
                        txtCarFee.setText("");
                        txtCarNumber.setText("");
                        
                        

                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(CarReg.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (SQLException ex) {
                        Logger.getLogger(CarReg.class.getName()).log(Level.SEVERE, null, ex);
                    }
            }
    }//GEN-LAST:event_btnAdd2ActionPerformed

    private void txtCarNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarNumberActionPerformed

    private void txtPaidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPaidKeyPressed

          if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
            String totle = txtTotle.getText();
            String paid = txtPaid.getText();

            int conTotle = Integer.parseInt(totle);
            int conPaid = Integer.parseInt(paid);

            int balance = conTotle - conPaid;

            txtBalance.setText(String.valueOf(balance));
            btnAdd2.setEnabled(true);
        }  
    }//GEN-LAST:event_txtPaidKeyPressed

    
    public int countTotle(int days, int amount){
        int fee = 0;
        fee = days * amount;   
        return fee;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public void get_table(){
        
        int c;
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/carrent","root","");
            pst = (PreparedStatement) con.prepareStatement("select * from rent");
            ResultSet rs = pst.executeQuery();
            
            ResultSetMetaData rm = rs.getMetaData();
            c = rm.getColumnCount();
            DefaultTableModel df = (DefaultTableModel)table1.getModel();
            df.setRowCount(0);
            
            while (rs.next()){
                Vector vector = new Vector();
                
                for (int i = 0; i <= c; i++) {
                    vector.add(rs.getString("rent_id"));
                    vector.add(rs.getString("car_id"));
                    vector.add(rs.getString("customer_id"));
                    vector.add(rs.getString("customer_name"));
                    vector.add(rs.getString("car_fee"));
                    vector.add(rs.getString("due_date"));
                    vector.add(rs.getString("trn_date"));
                    vector.add(rs.getString("totle_fee"));
                    vector.add(rs.getString("paid_amount"));
                    vector.add(rs.getString("balance"));
                    vector.add(rs.getString("car_number"));
                }
                df.addRow(vector);
            }
            
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RentCar.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(RentCar.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }
    
    
    
    
   
    
    
    
    public void autoId(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/carrent","root","");
            Statement s = con.createStatement(); 
            
            ResultSet rs = s.executeQuery("select Max(rent_id) from rent");
            rs.next();
            rs.getString("Max(rent_id)");
            
            if (rs.getString("Max(rent_id)")==null) {
                txtRentID.setText("R0001");
            }
            else
            {
                long id = Long.parseLong(rs.getString("Max(rent_id)").substring(2,rs.getString("Max(rent_id)").length()));
                id++;
                txtRentID.setText("R0" + String.format("%03d", id));
            }
            
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(RentCar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RentCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RentCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RentCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RentCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RentCar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd2;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCancel1;
    private javax.swing.JComboBox<String> comboCar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table1;
    private javax.swing.JTextField txtAvailable;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtCarFee;
    private javax.swing.JTextField txtCarNumber;
    private javax.swing.JTextField txtCusID;
    private javax.swing.JTextField txtCusName;
    private com.toedter.calendar.JDateChooser txtDate;
    private com.toedter.calendar.JDateChooser txtDueDate;
    private javax.swing.JTextField txtPaid;
    private javax.swing.JTextField txtRentID;
    private javax.swing.JTextField txtTotle;
    // End of variables declaration//GEN-END:variables
}
